
- name: Install Apache, a web server
  hosts: all
  tasks:
    - name: Ensure the httpd software is installed
      yum:
        name: httpd
        state: present
    - name: Ensure the httpd service is enabled and started
      service:
        name: httpd
        state: started
        enabled: yes
