- name: Install Tomcat Application server
  hosts: all
  tasks:
    - name: Ensure tomcat is installed
      yum:
        name: tomcat
        state: present
    - name: Ensure tomcat service is enabled and started
      service:
        name: tomcat
        enabled: yes
        state: started
      
