- name: Ping arbitrary destination from server
  hosts: all
  tasks:
  - name: "Ping {{ ping_target }} from {{ ansible_hostname }}"
    command: "ping -c 5 {{ ping_target }}"
    delegate_to: "{{ ansible_hostname }}"
    changed_when: false
    register: ping
  - name: Print output from ping
    debug:
      msg: "{{ ping.stdout }}"
