---
- name: Check if a server is alive
  hosts: all
  tasks:
  - name: Set TARGET_LOG_INFO
    ansible.builtin.set_fact:
      ansible_target_log_info = "{{ awx_job_id }}"
  
  - name: Log into the server and check that the ping modules returns output
    ansible.builtin.ping:
      data: pong from Ansible
